version: "3.3"

services:
  app:
    image: bb-identity-api-image
    ports:
      - 3344:3003
    networks:
      - web
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./mockoon-bbidentity.json:/mockoon-bbidentity.json

networks:
  web:
    driver: bridge
