openapi: 3.1.0
info:
  title: Credential Management APIs
  description: Credential Lifecylce Management APIs
  version: 1.0.0
  contact:
    url: 'https://www.govstack.global/'
paths:
  /retrieveUinByVid/{vid}:
    get:
      description: Retrieve UIN with Virtual ID
      parameters:
        - in: path
          name: vid
          schema:
            type: string
          required: true
          description: Virtual ID
      responses:
        200:
          description: Credential Issue Status
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  version:
                    type: string
                  responsetime:
                    type: string
                  metadata:
                    type: object
                  response:
                    type: object
                    properties:
                      vidStatus:
                        type: string
                      restoredVid:
                        type: object
                      UIN:
                        type: string
                      VID:
                        type: string
                  errors:
                    type: array
                    items:
                      properties:
                        errorCode:
                          type: string
                        message:
                          type: string
  /reqCredential:
    post:
      description: Request Credential
      requestBody:
        content: 
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                version:
                  type: string
                requesttime:
                  type: string
                request:
                  type: object
                  properties:
                    transactionID:
                      type: string
                    individualId:
                      type: string
                    otp:
                      type: string
                    credentialType:
                      type: string
                    encrypt:
                      type: boolean
                    issuer:
                      type: string
                    encryptionKey:
                      type: string
                    recepiant:
                      type: string
                    user:
                      type: string
                    sharableAttributes:
                      type: array
                      items:
                        type: string
                    additionalData:
                      type: object
                      properties:
                        property1:
                          type: object
                        property2:
                          type: object
      responses:
        200:
          description: Credential Request Successful
          content:
            application/json:
              schema:
                type: object
  /getCredentialStatus/{requestId}:
    get:
      description: Get credential issue status
      parameters:
        - in: path
          name: requestId
          schema:
            type: string
          required: true
          description: Request ID
      responses:
        200:
          description: Credential Issue Status
          content:
            application/json:
              schema:
                type: object
  /getCard/{requestId}:
    get:
      description: Get Card
      parameters:
        - in: path
          name: requestId
          schema:
            type: string
          required: true
          description: Request ID
      responses:
        200:
          description: Get Card Response
          content:
            application/json:
              schema:
                type: object
  /block:
    post:
      description: Block Credential
      requestBody:
        content: 
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                version:
                  type: string
                requesttime:
                  type: string
                metadata:
                  type: object
                request:
                  type: object
                  properties:
                    id:
                      type: string
                    idType:
                      type: string
                    status:
                      type: string
                    expiryTimestamp:
                      type: string
      responses:
        200:
          description: Credential Blocked
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  version:
                    type: string
                  responsetime:
                    type: string
                  metadata:
                    type: object
                  response:
                    type: object
                    properties:
                      id:
                        type: string
                      idType:
                        type: string
                      status:
                        type: string
                      expiryTimestamp:
                        type: string
                  errors:
                    type: array
                    items:
                      properties:
                        errorCode:
                          type: string
                        message:
                          type: string
  /unblock:
    post:
      description: Unblock Suspended Credential
      requestBody:
        content: 
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                version:
                  type: string
                requesttime:
                  type: string
                metadata:
                  type: object
                request:
                  type: object
                  properties:
                    id:
                      type: string
                    idType:
                      type: string
                    status:
                      type: string
                    expiryTimestamp:
                      type: string
      responses:
        200:
          description: Credential Unblocked
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  version:
                    type: string
                  responsetime:
                    type: string
                  metadata:
                    type: object
                  response:
                    type: object
                    properties:
                      id:
                        type: string
                      idType:
                        type: string
                      status:
                        type: string
                      expiryTimestamp:
                        type: string
                  errors:
                    type: array
                    items:
                      properties:
                        errorCode:
                          type: string
                        message:
                          type: string
